# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_data.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'sensor_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sensor_data.proto\"-\n\tDataPoint\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"7\n\x14TimeSeriesCollection\x12\x1f\n\x0b\x64\x61ta_points\x18\x01 \x03(\x0b\x32\n.DataPoint\"{\n\nSensorData\x12\'\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x17.SensorData.FieldsEntry\x1a\x44\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.TimeSeriesCollection:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATA_FIELDSENTRY']._loaded_options = None
  _globals['_SENSORDATA_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_DATAPOINT']._serialized_start=21
  _globals['_DATAPOINT']._serialized_end=66
  _globals['_TIMESERIESCOLLECTION']._serialized_start=68
  _globals['_TIMESERIESCOLLECTION']._serialized_end=123
  _globals['_SENSORDATA']._serialized_start=125
  _globals['_SENSORDATA']._serialized_end=248
  _globals['_SENSORDATA_FIELDSENTRY']._serialized_start=180
  _globals['_SENSORDATA_FIELDSENTRY']._serialized_end=248
# @@protoc_insertion_point(module_scope)
